name: CI

on: 
  push:
    branches:
      - master
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: build deploy
        env:
          GITHUB_NAME: ${{ secrets.ACCESS_NAME }}
          GITHUB_EMAIL: ${{ secrets.ACCESS_EMAIL }}
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          VSSUE_CLIENTID: ${{ secrets.VSSUE_CLIENTID }}
          VSSUE_CLIENTSECRET: ${{ secrets.VSSUE_CLIENTSECRET }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "module.exports={clientId: '${VSSUE_CLIENTID}',clientSecret: '${VSSUE_CLIENTSECRET}'}" > src/.vuepress/secret.js
          yarn && yarn build
          cd src/.vuepress/dist
          git config --global user.name "${GITHUB_NAME}"
          git config --global user.email "${GITHUB_EMAIL}"
          git init
          git add -A
          git commit -m "来自GitHub Action的自动部署：$(TZ="Asia/Shanghai" date +"%Y-%m-%d %T %Z")"
          git push -f git@github.com:qcyblm/qcyblm.github.io.git master:gh-pages
