name: vuepress-deploy
on: 
  push:
    branches:
      - master
env:
  LANG: zh_CN.UTF-8
  LANGUAGE: zh_CN
  TZ: Asia/Shanghai
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x
      - name: build and deploy
        env:
          GITHUB_NAME: ${{ secrets.ACCESS_NAME }}
          GITHUB_EMAIL: ${{ secrets.ACCESS_EMAIL }}
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          VSSUE_CLIENTID: ${{ secrets.VSSUE_CLIENTID }}
          VSSUE_CLIENTSECRET: ${{ secrets.VSSUE_CLIENTSECRET }}
        run: |
          yarn config set registry https://r.npm.taobao.org
          yarn
          echo "module.exports={clientId: '${VSSUE_CLIENTID}',clientSecret: '${VSSUE_CLIENTSECRET}'}" > src/.vuepress/secret.js
          yarn build
          rm -rf src/.vuepress/secret.js
          cd src/.vuepress/dist
          git config --global user.name "${GITHUB_NAME}"
          git config --global user.email "${GITHUB_EMAIL}"
          git init
          git add -A
          git commit -m "Auto Deploy from Github Actions: $(date +"%Y年%m月%d日 %T %Z")"
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com,192.30.255.113,140.82.112.4,140.82.113.3,140.82.112.3,140.82.114.3,140.82.113.4,140.82.121.4,140.82.114.4,52.74.223.119,13.229.188.59 >> ~/.ssh/known_hosts
          git push -f git@github.com:${GITHUB_NAME}/${GITHUB_NAME}.github.io.git master:gh-pages
          rm -rf ~/.ssh/known_hosts
